[package]
name = "gaiacom-sovereign-core"
version = "2.0.0"
edition = "2021"
rust-version = "1.85"
license = "AGPL-3.0-only"

[dependencies]
aes-gcm = "0.10.3"
aes-gcm-siv = "0.11.1"
chacha20poly1305 = "0.10.1"
ctr = "0.9.2"
eax = "0.5.0"
hkdf = "0.12.4"
hmac = "0.12.1"
serpent = "0.5.1"
sha3 = "0.10.8"
twofish = "0.7.1"
zeroize = { version = "1.8.2", features = ["derive"] }

[profile.release]
codegen-units = 1
lto = "fat"
opt-level = 3
panic = "abort"
strip = "symbols"
