[package]
name = "gaiacom-sovereign-wasm"
version = "2.0.0"
edition = "2021"
rust-version = "1.85"
license = "AGPL-3.0-only"

[lib]
crate-type = ["cdylib"]

[dependencies]
gaiacom-sovereign-core = { path = "../SovereignCryptoCore" }
getrandom = { version = "0.2.17", features = ["js"] }
hex = "0.4.3"
wasm-bindgen = "0.2.104"
zeroize = "1.8.2"

[package.metadata.wasm-pack.profile.release]
wasm-opt = false

[profile.release]
codegen-units = 1
lto = "fat"
opt-level = "s"
panic = "abort"
strip = "symbols"

